export const queryKeys = {
  devices: "devices",
  brands: "brands",
  models: "models",
  guides: "guides",
  steps: "steps",
  catagories: "catagories",
  ratings: "ratings",
  ratingValue: "ratingValue",
  Rating: "Rating",
  isHelpful: "isHelpful",
  ces: "ces",
  csat: "csat",
  nps: "nps",
  relevant: "relevant",
};
